# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from aios.v1 import operation_pb2 as aios_dot_v1_dot_operation__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aios/v1/operation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OperationInterfaceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Submit = channel.unary_unary(
                '/aios.v1.OperationInterface/Submit',
                request_serializer=aios_dot_v1_dot_operation__pb2.OperationEnvelope.SerializeToString,
                response_deserializer=aios_dot_v1_dot_operation__pb2.OperationView.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/aios.v1.OperationInterface/Cancel',
                request_serializer=aios_dot_v1_dot_operation__pb2.CancelRequest.SerializeToString,
                response_deserializer=aios_dot_v1_dot_operation__pb2.OperationView.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/aios.v1.OperationInterface/Get',
                request_serializer=aios_dot_v1_dot_operation__pb2.OperationIdRequest.SerializeToString,
                response_deserializer=aios_dot_v1_dot_operation__pb2.OperationView.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/aios.v1.OperationInterface/Watch',
                request_serializer=aios_dot_v1_dot_operation__pb2.WatchRequest.SerializeToString,
                response_deserializer=aios_dot_v1_dot_operation__pb2.OperationView.FromString,
                _registered_method=True)
        self.DescribeCapabilities = channel.unary_unary(
                '/aios.v1.OperationInterface/DescribeCapabilities',
                request_serializer=aios_dot_v1_dot_operation__pb2.Empty.SerializeToString,
                response_deserializer=aios_dot_v1_dot_operation__pb2.CapabilityReport.FromString,
                _registered_method=True)


class OperationInterfaceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Submit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescribeCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperationInterfaceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Submit': grpc.unary_unary_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=aios_dot_v1_dot_operation__pb2.OperationEnvelope.FromString,
                    response_serializer=aios_dot_v1_dot_operation__pb2.OperationView.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=aios_dot_v1_dot_operation__pb2.CancelRequest.FromString,
                    response_serializer=aios_dot_v1_dot_operation__pb2.OperationView.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=aios_dot_v1_dot_operation__pb2.OperationIdRequest.FromString,
                    response_serializer=aios_dot_v1_dot_operation__pb2.OperationView.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=aios_dot_v1_dot_operation__pb2.WatchRequest.FromString,
                    response_serializer=aios_dot_v1_dot_operation__pb2.OperationView.SerializeToString,
            ),
            'DescribeCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.DescribeCapabilities,
                    request_deserializer=aios_dot_v1_dot_operation__pb2.Empty.FromString,
                    response_serializer=aios_dot_v1_dot_operation__pb2.CapabilityReport.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aios.v1.OperationInterface', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aios.v1.OperationInterface', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OperationInterface(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.v1.OperationInterface/Submit',
            aios_dot_v1_dot_operation__pb2.OperationEnvelope.SerializeToString,
            aios_dot_v1_dot_operation__pb2.OperationView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.v1.OperationInterface/Cancel',
            aios_dot_v1_dot_operation__pb2.CancelRequest.SerializeToString,
            aios_dot_v1_dot_operation__pb2.OperationView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.v1.OperationInterface/Get',
            aios_dot_v1_dot_operation__pb2.OperationIdRequest.SerializeToString,
            aios_dot_v1_dot_operation__pb2.OperationView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aios.v1.OperationInterface/Watch',
            aios_dot_v1_dot_operation__pb2.WatchRequest.SerializeToString,
            aios_dot_v1_dot_operation__pb2.OperationView.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescribeCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aios.v1.OperationInterface/DescribeCapabilities',
            aios_dot_v1_dot_operation__pb2.Empty.SerializeToString,
            aios_dot_v1_dot_operation__pb2.CapabilityReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
